CANONICAL_CATEGORIES = [
    "Food & Dining",
    "Shopping",
    "Entertainment",
    "Travel",
    "Utilities",
    "Healthcare",
    "Education",
    "Investment",
    "Salary",
    "Transfer",
    "Refund",
    "EMI/Loan",
    "Insurance",
    "Fuel",
    "Groceries",
    "Other",
]

# Maps regex-categorizer codes (from analyzer.py) to canonical human-readable labels.
REGEX_TO_CANONICAL: dict[str, str] = {
    "E-COMMERCE": "Shopping",
    "FOOD_DELIVERY": "Food & Dining",
    "FOOD_EXPENSE": "Food & Dining",
    "PAYMENT_APP": "Transfer",
    "RETAIL": "Shopping",
    "TELECOM_BILL": "Utilities",
    "UTILITY_BILL": "Utilities",
    "TRAVEL": "Travel",
    "TRANSPORT": "Travel",
    "TRANSPORT_FUEL": "Fuel",
    "SUBSCRIPTION": "Entertainment",
    "LOAN_REPAYMENT": "EMI/Loan",
    "LOAN_DISBURSEMENT": "EMI/Loan",
    "HOUSING": "Utilities",
    "INCOME": "Salary",
    "EDUCATION": "Education",
    "INSURANCE": "Insurance",
    "INVESTMENT": "Investment",
    "HEALTH_EXPENSE": "Healthcare",
    "GROCERIES": "Groceries",
    "TAXES": "Other",
}
