"""initial schema: statements, transactions, corrections

Revision ID: 9670b8f28c89
Revises:
Create Date: 2026-06-21 20:08:05.674209

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "9670b8f28c89"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "corrections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fingerprint", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "corrected_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "corrected_merchant", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_corrections_fingerprint"), "corrections", ["fingerprint"], unique=True
    )
    op.create_table(
        "statements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "original_filename", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("account_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("bank_name", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("account_holder", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("period_from", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("period_to", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(), nullable=False),
        sa.Column("confidence_overall", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_statements_file_hash"), "statements", ["file_hash"], unique=True
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("statement_id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_date", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("amount", sa.Float(), nullable=True),
        sa.Column(
            "transaction_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("narration", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("balance", sa.Float(), nullable=True),
        sa.Column("payment_method", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("merchant", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("payment_gateway", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "transaction_reference", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("llm_enriched", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["statement_id"],
            ["statements.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("transactions")
    op.drop_index(op.f("ix_statements_file_hash"), table_name="statements")
    op.drop_table("statements")
    op.drop_index(op.f("ix_corrections_fingerprint"), table_name="corrections")
    op.drop_table("corrections")
    # ### end Alembic commands ###
