STATUS_CODES = {
    "SUCCESS": 200,
    "SUCCESS_NO_CONTENT": 204,
    "BAD_REQUEST": 400,
    "UNAUTHORIZED": 401,
    "FORBIDDEN": 403,
    "NOT_FOUND": 404,
    "METHOD_NOT_ALLOWED": 405,
    "REQUEST_TIMEOUT": 408,
    "CONFLICT": 409,
    "INTERNAL_SERVER_ERROR": 500,
    "BAD_GATEWAY": 502,
}

def get_status_code(key):
    return STATUS_CODES.get(key, 500)
